version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: myapp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: myapp_web
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=gov_scraper.settings
    depends_on:
      - redis

  worker:
    build: .
    container_name: myapp_worker
    command: poetry run celery -A gov_scraper worker -l info
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=gov_scraper.settings
    depends_on:
      - redis
      - app

volumes:
  redis_data:
